name: Terraform CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'modules/**'
      - 'envs/**'
      - 'versions.tf'
      - '.github/**'
  pull_request:
    paths:
      - 'modules/**'
      - 'envs/**'
      - 'versions.tf'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Which environment to plan'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod

jobs:
  plan_dev:
    if: github.event_name == 'pull_request' ||
      (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'dev')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6
      - name: Terraform Init (Dev)
        working-directory: envs/dev
        run: terraform init -input=false
      - name: Terraform Plan (Dev)
        working-directory: envs/dev
        run: terraform plan -out=tfplan

  plan_prod:
    if: github.event_name == 'pull_request' ||
      (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'prod')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6
      - name: Terraform Init (Prod)
        working-directory: envs/prod
        run: terraform init -input=false
      - name: Terraform Plan (Prod)
        working-directory: envs/prod
        run: terraform plan -out=tfplan

  apply_prod:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: plan_prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6
      - name: Terraform Init (Prod)
        working-directory: envs/prod
        run: terraform init -input=false
      - name: Terraform Apply (Prod)
        working-directory: envs/prod
        run: terraform apply -auto-approve tfplan
